### ISSUE TITLE
using LiteLLM? 

### ISSUE THREAD

**Issue by ishaan-jaff** [Dgarc359/todowheel#15]
Hi @Dgarc359 , thanks for starring LiteLLM https://github.com/BerriAI/litellm. Are you using it ? 

(sorry I could not find a better way to contact you)

**Comment by Dgarc359** [comment]
> Hi @Dgarc359 , thanks for starring LiteLLM https://github.com/BerriAI/litellm. Are you using it ?
> 
> (sorry I could not find a better way to contact you)

Hey there! Thanks for reaching out. This project _does not_ use litellm. I have a few side-projects that may end up leveraging it, but none are public yet.
